### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by ywgoout** [Davidham3/STGCN#4]
could you  please  put  pems  data  on  baiduyun  ?  very thanks

**Comment by sam101340** [comment]
hi
  could you tell me how to get the distance between stations trough raw data

thanks

**Comment by hupoxianxian** [comment]
If num_points_for_predict > 1, the project cannot work， maybe you lost some code ?

**Comment by Davidham3** [comment]
@sam101340 I used bing map api to get the distance between stations

**Comment by Davidham3** [comment]
@hupoxianxian I have updated all code.

**Comment by Davidham3** [comment]
@ywgoout I updated all the code yesterday. I replace my dataset with the dataset provided by authors [STGCN_IJCAI-18](https://github.com/VeritasYin/STGCN_IJCAI-18).
